### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by MrBuddyCasino** [gstamatelat/random-sampling#32]
It would be nice to have a thread-safe version of at least the best-performing algorithm (Lil). Other than that, very useful, thanks for making this available!

**Comment by MrBuddyCasino** [comment]
Actually, looks easy enough - I'll try my hand on it.

**Comment by gstamatelat** [comment]
@MrBuddyCasino Good catch! I didn't have thread safety in mind but it's a good addition. Please, reopen #33 whenever you feel comfortable with your changes. Thanks!

**Comment by MrBuddyCasino** [comment]
Reopened :)
